repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      args: ["--config=", ".github/pre-commit/pyproject.toml"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: ["--config=", ".github/pre-commit/flake8.conf"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy --config-file .github/pre-commit/mypy.ini "$@" || true' --
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", ".github/pre-commit/bandit.yaml", "-r", ""] 