name: CI/CD

on: [push]

env:
  PYTHON_DIRS: $(find . -name "*.py" -type f -not -path  './.*' -exec dirname {} \; | cut -d "/" -f 2 | uniq)
  COV_DIRS: $(echo ${{ env.PYTHON_DIRS }} | xargs -n1 -I{} echo "--cov={}")

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f .github/requirements.txt ]; then pip install -r .github/requirements.txt ; fi

    - name: Lint
      run: |
        flake8 --config=.github/config/flake8.conf ${{ env.PYTHON_DIRS }}
        mypy --config-file .github/config/mypy.ini ${{ env.PYTHON_DIRS }}
        interrogate -vv -i --fail-under=80

    - name: Security Check
      run: |
        bandit -c .github/config/bandit.yaml -r ${{ env.PYTHON_DIRS }}

    - name: Test
      run: |
        pytest \
          --junit-xml=".artefacts/test-report.xml" --html=".artefacts/test-report.html" --self-contained-html \
          --cov-report term-missing --cov=${{ env.COV_DIRS }} --cov-fail-under=0 \
          --log-cli-level=INFO --color=yes -x -v \  

    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        path: .artefacts/test-report.html